version: "3.9"

services:
  backend:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - .:/app
    command: python app.py

  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
      - /app/node_modules

    command: npm run serve
    depends_on:
      - backend
